name: Release Setup

on:
  workflow_call

jobs:
  release:
    name: "Continuous Release"
    runs-on: ubuntu-latest
    steps:
    - name: Job info
      run: |
        echo "GitHub Ref: ${{ github.ref }}"
    - name: Automatic release
      uses: "marvinpinto/action-automatic-releases@latest"
      if: github.ref == 'refs/heads/main'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "continuous"
        prerelease: true
        title: "Continuous release"
